// PM2 profile for safe always-on background services.
// These services do not mutate file organization state by default.
//
// Start (no terminal needed after this):
//   npm run pm2:background:start   # or: pm2 start ecosystem.background.config.js
//   pm2 save
// Then you can close the terminal. PM2 runs as a daemon; all apps (long-running
// and cron-scheduled) are managed by it. Cron jobs run at their scheduled times
// without an open terminal.
//
// Resurrect after reboot (run once, then follow the command it prints):
//   pm2 startup
//
// Notes:
// - QA/site_audit/content/github/lead pipelines are queue-driven task types.
//   They run through claw-worker-ai and claw-worker-nas.
// - Keep POLICY_USE_OPA=false until OPA endpoint is confirmed healthy.

"use strict";

const fs = require("fs");
const path = require("path");
const REPO = __dirname;
const MISSION_CONTROL_CONFIG = path.join(REPO, "config", "mission-control-agents.json");

function loadMissionControlAgents() {
  try {
    const raw = fs.readFileSync(MISSION_CONTROL_CONFIG, "utf8");
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.warn(`[ecosystem.background] mission-control config load failed: ${err.message}`);
    return [];
  }
}

const MISSION_CONTROL_AGENT_APPS = loadMissionControlAgents().map((agent) => ({
  name: `claw-mission-${String(agent.id || "").trim()}`,
  script: "scripts/mission-control-agent-runner.js",
  args: `--agent ${String(agent.id || "").trim()}`,
  cwd: REPO,
  watch: false,
  autorestart: false,
  cron_restart: String(agent.cron || "0 * * * *"),
  env: { NODE_ENV: "production" },
  log_date_format: "YYYY-MM-DD HH:mm:ss",
}));

module.exports = {
  apps: [
    {
      name: "claw-ollama",
      script: "ollama",
      args: "serve",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      env: {
        NODE_ENV: "production",
        OLLAMA_HOST: process.env.OLLAMA_HOST || "127.0.0.1:11434",
        OLLAMA_KEEP_ALIVE: "24h",
        OLLAMA_NUM_PARALLEL: "2",
        PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-dispatcher",
      script: "cli/run-dispatcher.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 8000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
        OLLAMA_HOSTS: process.env.OLLAMA_HOSTS || process.env.MODEL_FLEET_OLLAMA_HOSTS || "http://127.0.0.1:11434",
        OLLAMA_REMOTE_FIRST: process.env.OLLAMA_REMOTE_FIRST || "false",
        // 30 tasks/batch at 5s intervals gives ~360 dispatch opportunities/hour.
        // Raised from 25 to push daily throughput past the 30 tasks/day target.
        DISPATCH_BATCH_LIMIT: "30",
        POLICY_USE_OPA: "false",
        CLASSIFY_PROVIDER: "openai",
        MODEL_ROUTING_EXTRA_PROVIDERS: "deepseek,gemini",
        MODEL_ROUTING_ANTHROPIC_LAST: "true",
        ANTHROPIC_ALLOWED: "false",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-worker-nas",
      script: "workers/worker.js",
      instances: 3,
      exec_mode: "fork",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        NODE_ROLE: "nas_worker",
        WORKER_TAGS: "infra,deterministic,io_heavy,cpu_heavy",
        WORKER_ENFORCE_ROLE_TAG_POLICY: "true",
        WORKER_CONCURRENCY_INFRA: "3",
        WORKER_CONCURRENCY_IO_HEAVY: "2",
        WORKER_CONCURRENCY_CPU_HEAVY: "2",
        WORKER_LOCK_DURATION_MS: "180000",
        WORKER_STALLED_INTERVAL_MS: "60000",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
        OLLAMA_HOSTS: process.env.OLLAMA_HOSTS || process.env.MODEL_FLEET_OLLAMA_HOSTS || "http://127.0.0.1:11434",
        OLLAMA_REMOTE_FIRST: process.env.OLLAMA_REMOTE_FIRST || "false",
        POLICY_USE_OPA: "false",
        MODEL_ROUTING_EXTRA_PROVIDERS: "deepseek,gemini",
        MODEL_ROUTING_ANTHROPIC_LAST: "true",
        ANTHROPIC_ALLOWED: "false",
        PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-worker-ai",
      script: "workers/worker.js",
      instances: 4,
      exec_mode: "fork",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "768M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        NODE_ROLE: "ai_worker",
        WORKER_TAGS: "ai,qa",
        WORKER_ENFORCE_ROLE_TAG_POLICY: "true",
        WORKER_CONCURRENCY_AI: "2",
        WORKER_CONCURRENCY_QA: "3",
        WORKER_LOCK_DURATION_MS: "180000",
        WORKER_STALLED_INTERVAL_MS: "60000",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
        OLLAMA_HOSTS: process.env.OLLAMA_HOSTS || process.env.MODEL_FLEET_OLLAMA_HOSTS || "http://127.0.0.1:11434",
        OLLAMA_REMOTE_FIRST: process.env.OLLAMA_REMOTE_FIRST || "false",
        POLICY_USE_OPA: "false",
        MODEL_ROUTING_EXTRA_PROVIDERS: "deepseek,gemini",
        MODEL_ROUTING_ANTHROPIC_LAST: "true",
        ANTHROPIC_ALLOWED: "false",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-architect-api",
      script: "scripts/architect-api.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        ARCHITECT_PORT: "4051",
        ARCHITECT_HOST: process.env.ARCHITECT_HOST || "127.0.0.1",
        ARCHITECT_ALLOWED_ORIGINS:
          process.env.ARCHITECT_ALLOWED_ORIGINS || "http://localhost:4051,http://127.0.0.1:4051",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-auto-heal-3h",
      script: "scripts/auto-heal-cycle.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 */3 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // 3x daily: health → gaps → dead letters → security_sweep (if stale) → reconcile-deadletters; optional Gemini/DeepSeek fix suggestions
    {
      name: "claw-daily-fix-pulse",
      script: "scripts/daily-fix-pulse.js",
      args: "--analyze",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 6,14,22 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-webhook-server",
      script: "scripts/webhook-server.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        WEBHOOK_PORT: "4040",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-offgrid-meshtastic-bridge",
      script: "scripts/offgrid-meshtastic-bridge.py",
      interpreter: "python3",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "384M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        MESHTASTIC_BRIDGE_MODE: "serial",
        MESHTASTIC_DEVICE: "",
        MESHTASTIC_BLE_ADDRESS: "",
        MESHTASTIC_TCP_HOST: "",
        MESHTASTIC_TCP_PORT: "4403",
        MESHTASTIC_BRIDGE_POLL_SEC: "2",
        HOME_ASSISTANT_URL: "http://homeassistant.local:8123",
        HOME_ASSISTANT_TOKEN: "",
        OFFGRID_LIGHT_ENTITIES: "",
        OFFGRID_SENSOR_ENTITIES: "",
        OFFGRID_PRESENCE_ENTITIES: "",
        OLLAMA_HOST: "http://127.0.0.1:11434",
        OFFGRID_AI_MODEL: "llama3.2:3b",
        MESHTASTIC_HEARTBEAT_FILE: ".runtime/meshtastic-heartbeat.json",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-brand-control-plane",
      script: "scripts/brand-control-plane.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        BRAND_CONTROL_PORT: "4050",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-platform-daily",
      script: "scripts/platform-daily.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 9 * * *",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
        POLICY_USE_OPA: "false"
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-learning-journal-email",
      script: "scripts/learning-journal-agent.js",
      args: "--hours 24 --email-to jamonwidit@plushtrap.com",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "30 7 * * *",
      env: {
        NODE_ENV: "production",
        LEARNING_JOURNAL_EMAIL_TO: "jamonwidit@plushtrap.com",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-security-sweep",
      script: "scripts/security-sweep.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "17 * * * *",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
        POLICY_USE_OPA: "false",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-security-bind-guard",
      script: "scripts/security-bind-guard.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "23 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-repomap",
      script: "scripts/repomap-background.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "11 * * * *",
      env: {
        NODE_ENV: "production",
        REPOMAP_TARGETS: "$HOME/claw-architect,$HOME/claw-repos/payclaw,$HOME/claw-repos/claw-architect",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-repo-readiness-pulse",
      script: "scripts/repo-readiness-pulse.js",
      args: "--min-score 80 --notify-regressions --alert-drop 8",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "41 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-payclaw-drift-pulse",
      script: "scripts/payclaw-drift-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "13 * * * *",
      env: {
        NODE_ENV: "production",
        PAYCLAW_REPO_PATH: "$HOME/claw-repos/payclaw",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-pm2-failure-symbol-triage",
      script: "scripts/pm2-failure-symbol-triage.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "19 * * * *",
      env: {
        NODE_ENV: "production",
        PM2_TRIAGE_MAX_FINDINGS: "6",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-exemplar-repos",
      script: "scripts/exemplar-repos-from-reports.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 10 * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-daily-feature-rotation",
      script: "scripts/daily-feature-rotation.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "5 7 * * *",
      env: {
        NODE_ENV: "production",
        DAILY_FEATURE_ROTATION_PER_REPO: "2",
        DAILY_FEATURE_ROTATION_MAX_REPOS: "40",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-priority-repo-major-update-daily",
      script: "scripts/priority-repo-major-update-daily.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
        PRIORITY_REPO_PATTERNS: "quantfusion,cookiespass,tempecookiespass,payclaw,clawpay,roblox",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-symbolic-qa-hub",
      script: "scripts/symbolic-qa-hub.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "40 6 * * *",
      env: {
        NODE_ENV: "production",
        SYMBOLIC_QA_TOP_N: "12",
        SYMBOLIC_QA_ENQUEUE_IMPL: "true",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-closed-loop-daily",
      script: "scripts/closed-loop-daily.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "25 6 * * *",
      env: {
        NODE_ENV: "production",
        CLOSED_LOOP_DAILY_TARGETS:
          "local/quantfusion:cdp_network_contracts,local/quantfusion:symbol_failure_mapping,local/payclaw:auto_wait_stability,local/CookiesPass:wallet_pass_and_loyalty_flow,local/TempeCookiesPass:tempe_variant_stability,local/RobloxGitSync:game_quality_and_retention,local/claw-architect:symbol_failure_mapping",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-knowledge-troll-harvest",
      script: "scripts/knowledge-troll-harvest.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "7 * * * *",
      env: {
        NODE_ENV: "production",
        TROLL_REPO_LIMIT: "12",
        TROLL_PAPER_LIMIT: "8",
        TROLL_MAX_INDEX_TASKS: "18",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-pattern-robust-builder",
      script: "scripts/pattern-robust-builder.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "17 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-security-remediation-queue",
      script: "scripts/security-remediation-queue.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "22 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-dead-letter-reconcile",
      script: "scripts/dead-letter-reconcile.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 3 * * *",
      env: {
        NODE_ENV: "production",
        DLQ_LIVE_MODE: "false", // dry by default; set true (or pass --requeue) for live requeue
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-lead-autopilot-skynpatch",
      script: "scripts/lead-autopilot.js",
      args: "--daemon",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 10000,
      env: {
        NODE_ENV: "production",
        LEADGEN_BRAND_SLUG: "skynpatch",
        LEAD_AUTOPILOT_DAEMON: "true",
        LEAD_AUTOPILOT_INTERVAL_MIN: "15",
        LEAD_AUTOPILOT_TARGET_LEADS: "800",
        LEAD_AUTOPILOT_QUERY_LIMIT: "40",
        LEAD_AUTOPILOT_ENRICH_LIMIT: "180",
        LEAD_AUTOPILOT_SEND_MAX: "50",
        LEAD_AUTOPILOT_CITIES: "Scottsdale, AZ|Tempe, AZ|Phoenix, AZ|Mesa, AZ|Los Angeles, CA|Dallas, TX|Miami, FL|Chicago, IL|Atlanta, GA|San Diego, CA",
        LEAD_AUTOPILOT_QUERIES: "health food store|vitamin shop|wellness store|supplement store|natural foods store|gym fitness center|yoga studio|day spa|beauty supply store|cbd store",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-lead-autopilot-bws",
      script: "scripts/lead-autopilot.js",
      args: "--daemon",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 10000,
      env: {
        NODE_ENV: "production",
        LEADGEN_BRAND_SLUG: "blackwallstreetopoly",
        BWS_SCHEDULER_STATE_FILE: ".runtime/leadgen-state-blackwallstreetopoly.json",
        LEAD_AUTOPILOT_DAEMON: "true",
        LEAD_AUTOPILOT_DISABLE_SEND: "false",
        LEAD_AUTOPILOT_INTERVAL_MIN: "30",
        LEAD_AUTOPILOT_TARGET_LEADS: "400",
        LEAD_AUTOPILOT_QUERY_LIMIT: "25",
        LEAD_AUTOPILOT_ENRICH_LIMIT: "80",
        LEAD_AUTOPILOT_SEND_MAX: "12",
        LEAD_AUTOPILOT_CITIES: "Atlanta, GA|Houston, TX|Washington, DC|Nashville, TN|Charlotte, NC",
        LEAD_AUTOPILOT_QUERIES: "toy store|black owned boutique|hbcu shop|gift shop|bookstore",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-salesops-maintenance",
      script: "scripts/salesops-maintenance.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "30 8 * * *",
      env: {
        NODE_ENV: "production",
        SALESOPS_SEND_TEST_EMAILS: "false",
        SALESOPS_TEST_TO: "shop@skynpatch.com",
        SALESOPS_TEST_VARIANTS: "margin,sellthru",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-credit-autopilot",
      script: "scripts/credit-autopilot.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "5 * * * *",
      env: {
        NODE_ENV: "production",
        CREDIT_AUTOPILOT_LIMIT_PROFILES: "200",
        CREDIT_AUTOPILOT_LIMIT_DEADLINES: "200",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-credit-e2e-live-loop",
      script: "scripts/credit-e2e-live-loop.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "35 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-loyalty-maintenance",
      script: "scripts/loyalty-maintenance.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-ollama-maintenance",
      script: "scripts/ollama-maintenance.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
        OLLAMA_MAINT_TIMEOUT_MS: "20000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-system-cleanup",
      script: "scripts/system-cleanup.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "15 */6 * * *",
      env: {
        NODE_ENV: "production",
        SYSTEM_CLEANUP_RETENTION_DAYS: "14",
        SYSTEM_CLEANUP_REPORT_RETENTION_DAYS: "7",
        SYSTEM_CLEANUP_PM2_LOG_MAX_MB: "150",
        SYSTEM_CLEANUP_PM2_TRUNCATE_MB: "20",
        SYSTEM_CLEANUP_PM2_RESTART_HIGH_MEM: "true",
        SYSTEM_CLEANUP_PM2_RESTART_MB: "1024",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-backup-to-nas",
      script: "scripts/backup-to-nas.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "5 */2 * * *",
      env: {
        NODE_ENV: "production",
        BACKUP_DEVICE_NAME: "MacBook-Pro-2.local",
        NAS_BACKUP_ROOT: "/Volumes/home/Storage/_claw_backup",
        BACKUP_SOURCE_ROOTS: "$HOME/Downloads|$HOME/Dropbox|$HOME/claw-repos",
        BACKUP_MAX_FILES: "4000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-backup-verify-nas",
      script: "scripts/backup-verify-nas.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "35 */2 * * *",
      env: {
        NODE_ENV: "production",
        NAS_BACKUP_ROOT: "/Volumes/home/Storage/_claw_backup",
        BACKUP_REQUIRED_DEVICES: "MacBook-Pro-2.local,Tatsheens-Mini,Mac",
        BACKUP_VERIFY_FRESH_HOURS: "30",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-global-status-pulse",
      script: "scripts/global-redgreen-status.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/15 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-launch-e2e-matrix",
      script: "scripts/launch-e2e-matrix.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 */2 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-ai-work-pulse",
      script: "scripts/ai-work-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
        AI_WORK_PULSE_GITHUB_SCAN_LIMIT: "40",
        AI_WORK_PULSE_SIGNALS_LIMIT: "120",
        AI_WORK_PULSE_SIGNALS_DAYS: "14",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-backlog-orchestrator",
      script: "scripts/backlog-orchestrator.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-git-sites-subagent-pulse",
      script: "scripts/git-sites-subagent-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "10,40 * * * *",
      env: {
        NODE_ENV: "production",
        GIT_SUBAGENT_LOW_HEALTH_THRESHOLD: "95",
        GIT_SUBAGENT_LOW_HEALTH_LIMIT: "12",
        GIT_SUBAGENT_ALWAYS_SAMPLE: "true",
        GIT_SUBAGENT_SAMPLE_LIMIT: "20",
        GIT_SUBAGENT_PATTERNS: "auth,betterauth,multi_tenant,stripe,telnyx,maileroo,mailersend,email_flows,billing",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-github-scan-pulse",
      script: "scripts/github-observability-scan.js",
      args: "--limit 80 --strict-baseline --require-smoke-e2e",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "5 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-capability-factory-pulse",
      script: "scripts/capability-factory-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "15 * * * *",
      env: {
        NODE_ENV: "production",
        CAPABILITY_FACTORY_PULSE_MAX_REPOS: "24",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-saas-opportunity-researcher",
      script: "scripts/saas-opportunity-researcher.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "20 * * * *",
      env: {
        NODE_ENV: "production",
        SAAS_RESEARCH_LIMIT: "12",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-saas-pain-opportunity-report",
      script: "scripts/saas-pain-opportunity-report.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      // Weekly Monday 5:00 PM local time
      cron_restart: "0 17 * * 1",
      env: {
        NODE_ENV: "production",
        SAAS_PAIN_LIMIT: "160",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-weekly-trends-brief",
      script: "scripts/weekly-trends-brief.js",
      args: "--refresh",
      cwd: REPO,
      watch: false,
      autorestart: false,
      // Weekly Monday 5:35 PM local time
      cron_restart: "35 17 * * 1",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-db-janitor",
      script: "scripts/janitor-vacuum.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      // Weekly Sunday 2:00 AM local time (low-traffic period for DB maintenance)
      cron_restart: "0 2 * * 0",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-flow-regression-pulse",
      script: "scripts/flow-regression-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "20 * * * *",
      env: {
        NODE_ENV: "production",
        CLAW_REPOS_ROOT: "$HOME/claw-repos",
        FLOW_REGRESSION_REPO_LIMIT: "24",
        FLOW_REGRESSION_CONCURRENCY: "3",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-regression-autofix-pulse",
      script: "scripts/regression-autofix-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "25 * * * *",
      env: {
        NODE_ENV: "production",
        REGRESSION_AUTOFIX_MAX_REPOS: "6",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-utilization-autofill",
      script: "scripts/utilization-autofill-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
        UTIL_AUTOFILL_MIN_PENDING: "12",
        UTIL_AUTOFILL_MAX_ENQUEUE_PER_RUN: "20",
        UTIL_AUTOFILL_REPO_LIMIT: "8",
        UTIL_AUTOFILL_PATTERNS: "auth,betterauth,multi_tenant,stripe,telnyx,maileroo,mailersend,email_flows,billing",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-device-utilization-pulse",
      script: "scripts/device-utilization-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/2 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-needs-attention-autofix",
      script: "scripts/needs-attention-autofix-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-cookiespass-mission-pulse",
      script: "scripts/cookiespass-mission-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
        COOKIESPASS_TARGET_REPOS: "CookiesPass,TempeCookiesPass",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-resourceful-file-resolver",
      script: "scripts/resourceful-file-resolver.js",
      args: "--limit 1200",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-task-governor",
      script: "scripts/task-governor.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/15 * * * *",
      env: {
        NODE_ENV: "production",
        TASK_GOVERNOR_USE_LLM: process.env.TASK_GOVERNOR_USE_LLM || "false",
        TASK_GOVERNOR_TOOL_BUDGET_MAX_CALLS: process.env.TASK_GOVERNOR_TOOL_BUDGET_MAX_CALLS || "25",
        TASK_GOVERNOR_TOOL_BUDGET_MAX_TOKENS_PER_TOOL: process.env.TASK_GOVERNOR_TOOL_BUDGET_MAX_TOKENS_PER_TOOL || "12000",
        TASK_GOVERNOR_TOOL_BUDGET_MAX_TOKENS_TOTAL: process.env.TASK_GOVERNOR_TOOL_BUDGET_MAX_TOKENS_TOTAL || "120000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-system-4h-checkfix",
      script: "scripts/system-4h-checkfix.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 */4 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "clawpay-taskmaster-checkfix",
      script: "scripts/clawpay-taskmaster-checkfix.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 2,10,18 * * *",
      env: {
        NODE_ENV: "production",
        CLAWPAY_TASKMASTER_STALE_MINUTES: "40",
        CLAWPAY_CHECKFIX_TOOL_BUDGET_MAX_CALLS: process.env.CLAWPAY_CHECKFIX_TOOL_BUDGET_MAX_CALLS || "25",
        CLAWPAY_CHECKFIX_TOOL_BUDGET_MAX_TOKENS_PER_TOOL: process.env.CLAWPAY_CHECKFIX_TOOL_BUDGET_MAX_TOKENS_PER_TOOL || "12000",
        CLAWPAY_CHECKFIX_TOOL_BUDGET_MAX_TOKENS_TOTAL: process.env.CLAWPAY_CHECKFIX_TOOL_BUDGET_MAX_TOKENS_TOTAL || "90000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-qa-human-blocking",
      script: "scripts/qa-human-grade.js",
      args: "--blocking-only",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "35 */2 * * *",
      env: {
        NODE_ENV: "production",
        MCP_OPS_TOOL_BUDGET_MAX_CALLS: process.env.MCP_OPS_TOOL_BUDGET_MAX_CALLS || "25",
        MCP_OPS_TOOL_BUDGET_MAX_TOKENS_PER_TOOL: process.env.MCP_OPS_TOOL_BUDGET_MAX_TOKENS_PER_TOOL || "12000",
        MCP_OPS_TOOL_BUDGET_MAX_TOKENS_TOTAL: process.env.MCP_OPS_TOOL_BUDGET_MAX_TOKENS_TOTAL || "90000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-agent-memory-maintenance",
      script: "scripts/agent-memory-maintenance.js",
      args: "--keep-days 7",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "20 2 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-proactive-research-assistant",
      script: "scripts/proactive-research-assistant.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-self-awareness-index",
      script: "scripts/self-awareness-index.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-github-bootstrap-managed-repos",
      script: "scripts/github-bootstrap-managed-repos.js",
      args: "--limit 300",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "12 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-self-mod-worker",
      script: "scripts/self-mod-worker.js",
      args: "--max 1",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "10 */1 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-openclaw-coordinator",
      script: "scripts/openclaw-coordinator-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/5 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-coordinator-watchdog",
      script: "scripts/coordinator-watchdog-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *", // Run every 10 minutes
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-mcp-ops-agent",
      script: "scripts/mcp-ops-agent.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
        MCP_OPS_TOOL_BUDGET_MAX_CALLS: process.env.MCP_OPS_TOOL_BUDGET_MAX_CALLS || "25",
        MCP_OPS_TOOL_BUDGET_MAX_TOKENS_PER_TOOL: process.env.MCP_OPS_TOOL_BUDGET_MAX_TOKENS_PER_TOOL || "12000",
        MCP_OPS_TOOL_BUDGET_MAX_TOKENS_TOTAL: process.env.MCP_OPS_TOOL_BUDGET_MAX_TOKENS_TOTAL || "90000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-mcp-memory-consolidate",
      script: "scripts/mcp-memory-accelerator.js",
      args: "consolidate 1",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "15 2 * * *",
      env: {
        NODE_ENV: "production",
        MCP_CONSOLIDATE_DAYS: "1",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-mcp-benchmark-pack",
      script: "scripts/mcp-benchmark-pack.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "10 3 * * 1",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-mcp-inspector-contract",
      script: "scripts/mcp-inspector-contract-check.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "40 2 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-auto-recovery",
      script: "scripts/auto-recovery-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/5 * * * *", // Fallback pulse every 5 minutes
      env: {
        NODE_ENV: "production",
        AUTO_RECOVERY_MIN_ONLINE_AGENTS: "8",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-agent-fleet-manager",
      script: "scripts/agent-fleet-position-manager.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 3000,
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        FLEET_MANAGER_LOOP_SECONDS: "45",
        FLEET_MANAGER_MIN_ONLINE: "8",
        FLEET_MANAGER_MAX_ONLINE: "13",
        FLEET_AI_BACKLOG_THRESHOLD: "80",
        FLEET_AI_MIN_ON_PRESSURE: "3",
        FLEET_AI_AGING_PENDING_THRESHOLD: "60",
        FLEET_AI_SPIKE_TARGET: "4",
        FLEET_INFRA_BACKLOG_THRESHOLD: "50",
        FLEET_INFRA_MIN_ON_PRESSURE: "2",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-mission-heartbeat",
      script: "scripts/mission-control-heartbeat.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/15 * * * *",
      env: {
        NODE_ENV: "production",
        MISSION_CONTROL_STALE_MINUTES: "120",
        MISSION_CONTROL_RUN_PROGRESS_INTEGRITY_AUDIT: "1",
        MISSION_CONTROL_INTEGRITY_WINDOW_MINUTES: "60",
        MISSION_CONTROL_HEARTBEAT_FAIL_ON_ESCALATION: "1",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    ...MISSION_CONTROL_AGENT_APPS,
    // -----------------------------------------------------------------------
    // SRE autopilot: hourly triage + daily maintenance (ultra senior dev prompts)
    // Gathers PM2/logs/DLQ context, invokes LLM for blocker ID + fix recommendations.
    // Output: reports/sre-*-latest.json, ~/logs/infra-changes.md
    // -----------------------------------------------------------------------
    {
      name: "claw-sre-hourly-triage",
      script: "scripts/sre-hourly-triage.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 * * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-sre-daily-maintenance",
      script: "scripts/sre-daily-maintenance.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 3,15 * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // -----------------------------------------------------------------------
    // Uptime Watchdog — Hourly: finds what should run but isn't, restarts/starts/fixes
    // Subagents: PM2 checker, heartbeat checker, queue checker, recovery executor, diagnosis (LLM)
    // -----------------------------------------------------------------------
    {
      name: "claw-uptime-watchdog-hourly",
      script: "scripts/uptime-watchdog-hourly.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 * * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // -----------------------------------------------------------------------
    // Status Review Agents — Remediate schema integrity, security, worker stability, uptime
    // Coordinator orchestrates workflow, workers execute remediation tasks
    // -----------------------------------------------------------------------
    {
      name: "claw-status-review-coordinator",
      script: "scripts/status-review-agent-runner.js",
      args: "--agent status_review_coordinator",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-status-review-schema",
      script: "scripts/status-review-agent-runner.js",
      args: "--agent schema_integrity_agent",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 */2 * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-status-review-security",
      script: "scripts/status-review-agent-runner.js",
      args: "--agent security_remediation_agent",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 * * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-status-review-worker",
      script: "scripts/status-review-agent-runner.js",
      args: "--agent worker_stability_agent",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-status-review-uptime",
      script: "scripts/status-review-agent-runner.js",
      args: "--agent uptime_monitoring_agent",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/15 * * * *",
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // -----------------------------------------------------------------------
    // Nightly security council queue injector (3:30 AM — staggered from 4AM)
    // Inserts a security_council task into PostgreSQL so the agent dispatcher
    // picks it up and runs it through the full pipeline (retry, dedup, audit).
    //
    // Model routing (model-routing-policy.json):
    //   ollama → deepseek → gemini → openai → anthropic (last resort)
    //
    // To trigger manually: node scripts/queue-security-council.js
    // Dry-run: SECURITY_COUNCIL_DRY_RUN=true node scripts/queue-security-council.js
    // Fix commands via Discord #admin-agent: "fix C1" / "fix all critical"
    // -----------------------------------------------------------------------
    {
      name: "claw-security-council",
      script: "scripts/queue-security-council.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "30 3 * * *",
      env: {
        NODE_ENV: "production",
        SECURITY_COUNCIL_MAX_FILES: "80",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // -----------------------------------------------------------------------
    // OSS nightly code review (2:45 AM — runs before security council)
    // Indexes all managed repos and runs local static review passes.
    // No external paid API dependency required.
    // First-time setup: node scripts/greptile-code-review.js --index
    // -----------------------------------------------------------------------
    {
      name: "claw-oss-code-review",
      script: "scripts/greptile-code-review.js",
      args: "--nightly",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "45 2 * * *",
      env: {
        NODE_ENV: "production",
        GREPTILE_BRANCH: "main",
        GREPTILE_REMOTE: "github",
        CLAW_REPOS_ROOT: "$HOME/claw-repos",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-quantfusion-overnight-algo-dev",
      script: "scripts/quantfusion-overnight-algo-dev.js",
      args: "--mode paper",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "15 4 * * *",
      env: {
        NODE_ENV: "production",
        QUANT_MODE: "paper",
        QUANT_AGENT_ID: "quantfusion-core",
        QUANT_SYMBOLS: "SPY,QQQ,BTCUSD",
        QUANT_EQUITY_USD: "10000"
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // -----------------------------------------------------------------------
    // OpenGoat org pulse (2:00 AM daily)
    // Executive agents read activity signals and evolve org docs:
    // MISSION.md, VISION.md, STRATEGY.md, KPIs.md, ROADMAP.md
    // CEO synthesizes across all agents. Posts CEO weekly note to #monitoring.
    // -----------------------------------------------------------------------
    {
      name: "claw-opengoat-pulse",
      script: "scripts/opengoat-org-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 2 * * *",
      env: {
        NODE_ENV: "production",
        OPENGOAT_ORG_MODEL: "claude-sonnet-4-5-20250929",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // -----------------------------------------------------------------------
    // Prompt Oracle commerce bot (always-on)
    // Handles the $1 bot prompt purchase flow on Telegram.
    // Also runs the payment webhook server on port 3031 to receive confirmations
    // from Stripe Checkout webhooks.
    // Discord commerce is handled inline by discord-gateway.js (!oracle command).
    // -----------------------------------------------------------------------
    {
      name: "claw-discord-gateway",
      script: "scripts/discord-gateway.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        DISCORD_OPTIONAL: "true",
        DISCORD_ENABLE_MESSAGE_CONTENT_INTENT: "false",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-prompt-oracle",
      script: "scripts/bot-commerce.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      env: {
        NODE_ENV: "production",
        COMMERCE_PORT: "3031",
        ORACLE_MODEL: "claude-sonnet-4-5-20250929",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // Bot-to-Bot Commerce API (for autonomous agents)
    // Enables bots to purchase prompts programmatically via API
    {
      name: "claw-bot-commerce-api",
      script: "scripts/bot-commerce-api.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      env: {
        NODE_ENV: "production",
        BOT_COMMERCE_API_PORT: "3032",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    // Bot discovery and outreach (automated lead generation)
    // Discovers bots on Discord, Telegram, WhatsApp and sends outreach messages
    {
      name: "claw-bot-discovery",
      script: "scripts/bot-lead-discovery.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 9 * * *", // Daily at 9 AM
      env: {
        NODE_ENV: "production",
        BOT_DISCOVERY_KEYWORDS: "bot,claw,ai,agent,assistant,automation",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-bot-outreach",
      script: "scripts/bot-outreach.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 */6 * * *", // Every 6 hours
      env: {
        NODE_ENV: "production",
        BOT_OUTREACH_LIMIT: "50",
        BOT_OUTREACH_MAX_PER_PLATFORM: "40",
        BOT_OUTREACH_DELAY_MS: "1500",
        BOT_OUTREACH_JITTER_MS: "750",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-bot-sales-research-daily",
      script: "scripts/bot-sales-research-daily.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 15 * * *", // Daily at 3 PM
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-moltbook-harvester",
      script: "scripts/moltbook-harvester-responder.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "20 */2 * * *", // every 2 hours
      env: {
        NODE_ENV: "production",
        MOLTBOOK_HARVEST_SOURCES: "moltbook,reddit",
        MOLTBOOK_HARVEST_MAX_POSTS: "120",
        MOLTBOOK_MIN_INTENT_SCORE: "70",
        MOLTBOOK_AUTO_REPLY: "false",
        MOLTBOOK_MAX_REPLIES: "15",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "clawpay-task-master",
      script: "scripts/clawpay-task-master.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        CLAWPAY_TASKMASTER_LOOP_SECONDS: "600",
        CLAWPAY_DISCOVERY_EVERY_MINUTES: "120",
        CLAWPAY_OUTREACH_EVERY_MINUTES: "60",
        CLAWPAY_RESEARCH_EVERY_MINUTES: "1440",
        CLAWPAY_KAIZEN_EVERY_MINUTES: "60",
        CLAWPAY_TOOL_BUDGET_MAX_CALLS: process.env.CLAWPAY_TOOL_BUDGET_MAX_CALLS || "25",
        CLAWPAY_TOOL_BUDGET_MAX_TOKENS_PER_TOOL: process.env.CLAWPAY_TOOL_BUDGET_MAX_TOKENS_PER_TOOL || "12000",
        CLAWPAY_TOOL_BUDGET_MAX_TOKENS_TOTAL: process.env.CLAWPAY_TOOL_BUDGET_MAX_TOKENS_TOTAL || "120000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "clawpay-kaizen-swarm",
      script: "scripts/clawpay-kaizen-swarm.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "15 * * * *", // hourly kaizen loop
      env: {
        NODE_ENV: "production",
        CLAWPAY_TARGET_CREDITS: "100000",
        CLAWPAY_TARGET_DAYS: "90",
        CLAWPAY_KAIZEN_EXECUTE: "true",
        CLAWPAY_KAIZEN_RUN_LEARNING: "true",
        CLAWPAY_KAIZEN_TOOL_BUDGET_MAX_CALLS: process.env.CLAWPAY_KAIZEN_TOOL_BUDGET_MAX_CALLS || "25",
        CLAWPAY_KAIZEN_TOOL_BUDGET_MAX_TOKENS_PER_TOOL: process.env.CLAWPAY_KAIZEN_TOOL_BUDGET_MAX_TOKENS_PER_TOOL || "12000",
        CLAWPAY_KAIZEN_TOOL_BUDGET_MAX_TOKENS_TOTAL: process.env.CLAWPAY_KAIZEN_TOOL_BUDGET_MAX_TOKENS_TOTAL || "100000",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-overnight-advisory-board",
      script: "scripts/overnight-advisory-board.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 0 * * *",
      env: {
        NODE_ENV: "production",
        ADVISORY_MODEL_EXPERT: "claude-sonnet-4-5-20250929",
        ADVISORY_MODEL_MODERATOR: "claude-opus-4-5-20251101",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-autonomy-pr-cycle",
      script: "scripts/autonomous-pr-cycle.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 4 * * *",
      env: {
        NODE_ENV: "production",
        AUTONOMOUS_PR_ENABLE_PUSH: "true",
        AUTONOMOUS_PR_CREATE: "true",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-overnight-maintenance",
      script: "scripts/overnight-self-maintenance.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 4 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-overnight-backup",
      script: "scripts/overnight-backup-sanitize-push.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "30 4 * * *",
      env: {
        NODE_ENV: "production",
        BACKUP_REPO_BRANCH: "main",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-events-consumer",
      script: "scripts/events-domain-consumer.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      max_memory_restart: "384M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-events-spawner",
      script: "scripts/events-domain-spawner.js",
      cwd: REPO,
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      max_memory_restart: "256M",
      min_uptime: "10s",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-finance-queue",
      script: "scripts/finance-automation-queue.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/15 * * * *",
      env: {
        NODE_ENV: "production",
        FINANCE_QUEUE_BATCH_LIMIT: "30",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-model-routing-watchdog",
      script: "scripts/model-routing-watchdog.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/15 * * * *",
      env: {
        NODE_ENV: "production",
        MODEL_ROUTING_EXTRA_PROVIDERS: "deepseek,gemini",
        MODEL_ROUTING_ANTHROPIC_LAST: "true",
        ANTHROPIC_ALLOWED: "false",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-quantfusion-queue",
      script: "scripts/quantfusion-trading-queue.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
        QUANT_QUEUE_PAPER_ONLY: "true",
        QUANT_QUEUE_BATCH_LIMIT: "20",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-marketplace-os",
      script: "scripts/marketplace-services-os.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/20 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-agency-growth-os",
      script: "scripts/agency-growth-os.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "30 */2 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-roblox-growth-pulse",
      script: "scripts/roblox-game-growth-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/10 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-goal-autopilot",
      script: "scripts/goal-autopilot.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-production-kpi-flywheel",
      script: "scripts/production-kpi-flywheel.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "11 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-forward-progress-enforcer",
      script: "scripts/forward-progress-enforcer.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-agent-streamline-pulse",
      script: "scripts/agent-streamline-pulse.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "47 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      // experiment-engine is a one-shot CLI (exits after --run-all). Run nightly via cron only.
      // autorestart: false + max_restarts: 0 prevents crash loop (PM2 would otherwise restart on exit).
      // If already in loop: pm2 delete claw-experiment-engine && pm2 start ecosystem.background.config.js --only claw-experiment-engine
      name: "claw-experiment-engine",
      script: "scripts/experiment-engine.js",
      args: "--run-all",
      cwd: REPO,
      watch: false,
      autorestart: false,
      max_restarts: 0,
      cron_restart: "0 2 * * *",
      kill_timeout: 30000,
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "192.168.1.164",
        REDIS_PORT: "16379",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-clawhub-skill-factory",
      script: "scripts/clawhub-skill-factory.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "40 */2 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-team-pa-coordinator",
      script: "scripts/agent-team-cycle.js",
      args: "--agent pa_coordinator --refresh",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 8 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-team-x-growth",
      script: "scripts/agent-team-cycle.js",
      args: "--agent x_growth --refresh",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "10 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-team-opportunities-scout",
      script: "scripts/agent-team-cycle.js",
      args: "--agent opportunities_scout --refresh",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "15 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-team-trading-paper",
      script: "scripts/agent-team-cycle.js",
      args: "--agent trading_paper --refresh",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "*/30 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-team-security-monitor",
      script: "scripts/agent-team-cycle.js",
      args: "--agent security_monitor --refresh",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "20 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-team-builder",
      script: "scripts/agent-team-cycle.js",
      args: "--agent builder --refresh",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "25 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-repo-readiness-pulse",
      script: "scripts/repo-readiness-pulse.js",
      args: "--min-score 80 --notify-regressions --alert-drop 8",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "41 * * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claw-todo-6am-pull",
      script: "scripts/todo-6am-pull.js",
      cwd: REPO,
      watch: false,
      autorestart: false,
      cron_restart: "0 6 * * *",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
